#!/usr/bin/env node
// Generates src/tokens/design.tokens.stylex.ts and src/tokens/design.tokens.css
// from the W3C Design Tokens (DTCG) source in src/tokens/design.tokens.json,
// via Style Dictionary. Both are committed output, not built at install time.
// The .stylex.ts suffix is required, not stylistic: @stylexjs/babel-plugin's
// cross-file variable resolution only recognizes theme files whose name ends
// in .stylex.ts/.stylex.js (unstable_moduleResolution.themeFileExtension,
// defaults to '.stylex') — a plain design.tokens.ts fails to build.
//
// design.tokens.css is the public override contract. StyleX hashes every
// defineVars() custom property name in production output (confirmed against
// a real build: `--x1y97bz8`, not `--color-primary`), so those names can't
// serve as a stable API for an app that doesn't run the StyleX toolchain
// itself. Every StyleX var's value is therefore `var(--kui-*, <literal>)`
// rather than a bare literal — any consumer can override a token by
// redeclaring that custom property in their own stylesheet, regardless of
// their build tooling, and design.tokens.css documents the full set in one
// place. The inline fallback is required, not defensive: without it, a
// consumer who never sets the custom property at all (i.e. hasn't opted
// into overriding anything) gets an *unresolvable* var() and the property
// using it — background-color, font-size, whatever — drops to its CSS
// initial value. Confirmed by building the package and rendering Button
// with only dist/assets/stylex.css loaded and no override in scope: with a
// bare `var(--kui-color-primary)` and no fallback, the button rendered
// fully transparent with black text. The fallback makes design.tokens.css
// (and every override custom property) opt-in rather than mandatory.
//
// Dual-purpose: run directly (`npm run tokens:build`) for a one-shot
// regenerate, or import registerFormats/styleDictionaryConfig from
// vite.config.ts / tsdown.config.ts to drive the same build automatically
// via unplugin-style-dictionary — see the CLI guard at the bottom.
import { readFileSync } from 'node:fs'

import { format as oxfmtFormat } from 'oxfmt'
import StyleDictionary from 'style-dictionary'

/**
 * @typedef {import('style-dictionary/types').TransformedToken} TransformedToken
 * @typedef {[name: string, value: string]} Entry
 * @typedef {[name: string, light: string, dark: string]} ThemedEntry
 * @typedef {{ offsetX: string, offsetY: string, blur: string, spread: string, color: string }} ShadowLayer
 * @typedef {[x1: number, y1: number, x2: number, y2: number]} CubicBezier
 */

const STYLEX_BANNER = `// AUTO-GENERATED by scripts/build-tokens.mjs from the sibling design.tokens.json.
// Do not hand-edit — change design.tokens.json and run \`npm run tokens:build\`.
// The .stylex.ts suffix is required by @stylexjs/babel-plugin for cross-file
// variable resolution — see the comment at the top of build-tokens.mjs.

`

const CSS_BANNER = `/* AUTO-GENERATED by scripts/build-tokens.mjs from the sibling design.tokens.json.
   Do not hand-edit — change design.tokens.json and run \`npm run tokens:build\`.
   This is kanso-ui's public theming contract: override any custom property
   below (e.g. in your app's global stylesheet, after importing this file)
   to retheme every Kanso component — see the comment at the top of
   build-tokens.mjs. */

`

// The CSS custom-property namespace every generated variable lives under,
// and the segment each token group maps to within it. Deliberately singular
// even where the JS export for the same group is plural (`radii`, `shadows`)
// — matches how design systems conventionally name individual CSS custom
// properties (`--kui-radius-lg`, not `--kui-radii-lg`).
const CSS_VAR_PREFIX = 'kui'
/** @type {Record<string, string>} */
const CSS_CATEGORY = {
  colors: 'color',
  motion: 'motion',
  radii: 'radius',
  shadows: 'shadow',
  spacing: 'spacing',
  stateLayerOpacity: 'state-layer-opacity',
  typography: 'typography',
}

/** @param {string} key @returns {string} */
function pascalCase(key) {
  return key.charAt(0).toUpperCase() + key.slice(1)
}

/** @param {string} key @returns {string} */
function kebabCase(key) {
  return key.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`)
}

/** @param {string} fontName @returns {string} */
function quoteIfNeeded(fontName) {
  return fontName.includes(' ') ? `'${fontName}'` : fontName
}

/** @param {string} group @param {string} key @returns {string} */
function cssVarName(group, key) {
  return `--${CSS_VAR_PREFIX}-${CSS_CATEGORY[group]}-${kebabCase(key)}`
}

// Rewrites a category's defineVars entries so each value falls back through
// its public CSS custom property — see the file header for why the
// fallback (not just the var() reference) is required. JSON.stringify, not
// a hand-wrapped template literal, because the fallback can itself contain
// single quotes (font-family entries quote individual names, e.g. 'Roboto
// Serif') that would otherwise prematurely close a '...'-wrapped result.
/** @param {string} group @param {Entry[]} entries @returns {Entry[]} */
function withCssVarFallback(group, entries) {
  return entries.map(([key, value]) => [
    key,
    JSON.stringify(
      `var(${cssVarName(group, key)}, ${unquoteJsStringLiteral(value)})`,
    ),
  ])
}

// Strips exactly one layer of matching outer quotes from a JS string
// literal (as embedded by the *Entries functions below, ready to splice
// into a stylex.defineVars() call) to get the equivalent raw CSS value —
// e.g. "'400'" -> 400, '"Roboto Flex, sans-serif"' -> "Roboto Flex,
// sans-serif". Font-stack entries keep their inner quotes (needed by CSS
// too, for family names containing spaces); only the outer JS-string
// delimiter comes off.
/** @param {string} jsLiteral @returns {string} */
function unquoteJsStringLiteral(jsLiteral) {
  const quote = jsLiteral[0]
  if ((quote === "'" || quote === '"') && jsLiteral.at(-1) === quote) {
    return jsLiteral.slice(1, -1)
  }
  return jsLiteral
}

// $value is typed `any` by style-dictionary itself (a DTCG token's value is
// polymorphic depending on $type), so callers that need more than a plain
// string narrow the result through one of the type guards below.
/** @param {TransformedToken[]} allTokens @param {...string} path @returns {any} */
function byPath(allTokens, ...path) {
  const joined = path.join('.')
  const token = allTokens.find((t) => t.path.join('.') === joined)
  if (!token) throw new Error(`Missing token: {${joined}}`)
  return token.$value
}

/** @param {unknown} value @returns {value is string[]} */
function isStringArray(value) {
  return Array.isArray(value) && value.every((v) => typeof v === 'string')
}

/** @param {unknown} value @returns {value is ShadowLayer} */
function isShadowLayer(value) {
  return (
    typeof value === 'object' &&
    value !== null &&
    'offsetX' in value &&
    typeof value.offsetX === 'string' &&
    'offsetY' in value &&
    typeof value.offsetY === 'string' &&
    'blur' in value &&
    typeof value.blur === 'string' &&
    'spread' in value &&
    typeof value.spread === 'string' &&
    'color' in value &&
    typeof value.color === 'string'
  )
}

/** @param {unknown} value @returns {value is ShadowLayer[]} */
function isShadowLayerArray(value) {
  return Array.isArray(value) && value.every(isShadowLayer)
}

/** @param {unknown} value @returns {value is CubicBezier} */
function isCubicBezier(value) {
  return (
    Array.isArray(value) &&
    value.length === 4 &&
    value.every((v) => typeof v === 'number')
  )
}

// defineConsts, not defineVars: the compiler inlines these at every use
// site instead of emitting a custom property, which is the only thing that
// works for a value that has to sit inside an at-rule condition. There is
// deliberately no withCssVarFallback here and no matching entry in
// cssSource — see the note on layout.breakpoint in design.tokens.json.
/** @param {string} exportName @param {Entry[]} entries @returns {string} */
function defineConstsBlock(exportName, entries) {
  const lines = entries
    .map(([name, value]) => `  ${name}: ${value},`)
    .toSorted((a, b) => a.trim().localeCompare(b.trim()))
  return `const ${exportName} = stylex.defineConsts({
${lines.join('\n')}
})

export { ${exportName} }`
}

/** @param {string} exportName @param {Entry[]} entries @returns {string} */
function defineVarsBlock(exportName, entries) {
  const lines = entries
    .map(([name, value]) => `  ${name}: ${value},`)
    .toSorted((a, b) => a.trim().localeCompare(b.trim()))
  return `const ${exportName} = stylex.defineVars({
${lines.join('\n')}
})

export { ${exportName} }`
}

// Colors are the one group StyleX itself still needs to know is themed —
// unlike every other category, `[DARK]` gives each var a *different*
// fallback per scheme, which a single var(..., fallback) can't express.
/** @param {string} exportName @param {ThemedEntry[]} entries @returns {string} */
function themedVarsBlock(exportName, entries) {
  const lines = entries
    .map(([name, light, dark]) => {
      // JSON.stringify rather than a hand-wrapped '...' literal — see
      // withCssVarFallback above; colors are hex-only today so it isn't
      // live, but the two generators should stay consistent.
      const ref = (/** @type {string} */ value) =>
        JSON.stringify(`var(${cssVarName('colors', name)}, ${value})`)
      return `  ${name}: { [DARK]: ${ref(dark)}, default: ${ref(light)} },`
    })
    .toSorted((a, b) => a.trim().localeCompare(b.trim()))
  return `const ${exportName} = stylex.defineVars({
${lines.join('\n')}
})

export { ${exportName} }`
}

// A stylex.createTheme() pair per themed var group: overrideable classes
// that pin every var to an explicit light or dark value, regardless of the
// OS-level prefers-color-scheme media query design.tokens.css defaults to.
// A manual toggle (Storybook's dark-mode addon, or any future in-app theme
// switcher) needs both directions — forcing dark isn't enough on its own,
// since forcing *light* against a dark OS preference is exactly as common a
// case and would otherwise silently fall through to the media query.
/** @param {string} exportName @param {ThemedEntry[]} entries @returns {string} */
function themeOverrideBlocks(exportName, entries) {
  /** @param {'light' | 'dark'} mode @param {0 | 1} valueIndex @returns {string} */
  const build = (mode, valueIndex) => {
    const lines = entries
      .map(([name, ...values]) => `  ${name}: '${values[valueIndex]}',`)
      .toSorted((a, b) => a.trim().localeCompare(b.trim()))
    const themeExportName = `${exportName}${pascalCase(mode)}Theme`
    return `const ${themeExportName} = stylex.createTheme(${exportName}, {
${lines.join('\n')}
})

export { ${themeExportName} }`
  }
  return `${build('light', 0)}

${build('dark', 1)}`
}

/** @param {ShadowLayer[]} layers @returns {string} */
function serializeShadowLayers(layers) {
  return layers
    .map((l) => `${l.offsetX} ${l.offsetY} ${l.blur} ${l.spread} ${l.color}`)
    .join(', ')
}

/** @param {TransformedToken[]} allTokens @returns {string[]} */
function colorKeys(allTokens) {
  return [
    ...new Set(
      allTokens
        .filter((t) => t.path[0] === 'semantic' && t.path[1] === 'light')
        .map((t) => t.path[2]),
    ),
  ]
}

/** @param {TransformedToken[]} allTokens @returns {ThemedEntry[]} */
function colorThemedEntries(allTokens) {
  return colorKeys(allTokens).map((key) => [
    key,
    byPath(allTokens, 'semantic', 'light', key),
    byPath(allTokens, 'semantic', 'dark', key),
  ])
}

// The full 15-style type scale (display/headline/title/body/label ×
// large/medium/small) — see typography.scale in design.tokens.json.
const SCALE_STYLES = [
  'displayLarge',
  'displayMedium',
  'displaySmall',
  'headlineLarge',
  'headlineMedium',
  'headlineSmall',
  'titleLarge',
  'titleMedium',
  'titleSmall',
  'bodyLarge',
  'bodyMedium',
  'bodySmall',
  'labelLarge',
  'labelMedium',
  'labelSmall',
]

/** @param {TransformedToken[]} allTokens @returns {Entry[]} */
function typographyEntries(allTokens) {
  /** @type {Entry[]} */
  const entries = []
  for (const key of ['brand', 'plain', 'mono']) {
    /** @type {unknown} */
    const value = byPath(allTokens, 'typography', 'fontFamily', key)
    if (!isStringArray(value)) {
      throw new TypeError(`Expected string[] for typography.fontFamily.${key}`)
    }
    entries.push([
      `fontFamily${pascalCase(key)}`,
      `"${value.map(quoteIfNeeded).join(', ')}"`,
    ])
  }
  for (const key of ['regular', 'medium', 'bold']) {
    entries.push([
      `weight${pascalCase(key)}`,
      `'${byPath(allTokens, 'typography', 'fontWeight', key)}'`,
    ])
  }
  for (const style of SCALE_STYLES) {
    /** @type {unknown} */
    const font = byPath(allTokens, 'typography', 'scale', style, 'font')
    if (!isStringArray(font)) {
      throw new TypeError(
        `Expected string[] for typography.scale.${style}.font`,
      )
    }
    entries.push([`${style}Font`, `"${font.map(quoteIfNeeded).join(', ')}"`])
    for (const field of ['size', 'lineHeight', 'tracking', 'weight']) {
      entries.push([
        `${style}${pascalCase(field)}`,
        `'${byPath(allTokens, 'typography', 'scale', style, field)}'`,
      ])
    }
  }
  return entries
}

/** @param {TransformedToken[]} allTokens @returns {Entry[]} */
function spacingEntries(allTokens) {
  const keys = ['xxs', 'xs', 'sm', 'md', 'lg', 'xl', 'xxl', 'xxxl']
  return keys.map((key) => [
    key,
    `'${byPath(allTokens, 'spacing', 'component', key)}'`,
  ])
}

/** @param {TransformedToken[]} allTokens @returns {Entry[]} */
function radiiEntries(allTokens) {
  const keys = ['none', 'xs', 'sm', 'md', 'lg', 'xl', 'full']
  return keys.map((key) => [
    key,
    `'${byPath(allTokens, 'radii', 'component', key)}'`,
  ])
}

// Elevation shadows render as a fixed black in both light and dark schemes
// — dark mode instead conveys elevation via the surface-container tones in
// semantic.*, not a shadow-opacity shift. So unlike colors, shadows need no
// light/dark split.
/** @param {TransformedToken[]} allTokens @param {string} level @returns {string} */
function shadowLayersAt(allTokens, level) {
  /** @type {unknown} */
  const value = byPath(allTokens, 'shadow', level)
  if (!isShadowLayerArray(value)) {
    throw new TypeError(`Expected ShadowLayer[] for shadow.${level}`)
  }
  return serializeShadowLayers(value)
}

/** @param {TransformedToken[]} allTokens @returns {Entry[]} */
function shadowsEntries(allTokens) {
  return ['1', '2', '3', '4', '5'].map((level) => [
    `elevation${level}`,
    `'${shadowLayersAt(allTokens, level)}'`,
  ])
}

// Flattened to durationShort2 / easingStandard rather than kept nested,
// matching how typography collapses scale.labelLarge.size to
// labelLargeSize — stylex.defineVars() takes a flat object, so a nested
// group has to be flattened somewhere regardless.
const DURATION_STEPS = [
  'short1',
  'short2',
  'short3',
  'medium1',
  'medium2',
  'medium3',
  'long1',
  'long2',
  'long3',
]

const EASING_CURVES = [
  'emphasized',
  'emphasizedDecelerate',
  'emphasizedAccelerate',
  'standard',
  'springFast',
  'springSlow',
]

/** @param {TransformedToken[]} allTokens @param {string} curve @returns {string} */
function cubicBezierAt(allTokens, curve) {
  /** @type {unknown} */
  const value = byPath(allTokens, 'motion', 'easing', curve)
  if (!isCubicBezier(value)) {
    throw new TypeError(
      `Expected [number, number, number, number] for motion.easing.${curve}`,
    )
  }
  return `cubic-bezier(${value.join(', ')})`
}

/** @param {TransformedToken[]} allTokens @returns {Entry[]} */
function motionEntries(allTokens) {
  return [
    ...DURATION_STEPS.map(
      /** @returns {Entry} */
      (step) => [
        `duration${pascalCase(step)}`,
        `'${byPath(allTokens, 'motion', 'duration', step)}'`,
      ],
    ),
    ...EASING_CURVES.map(
      /** @returns {Entry} */
      (curve) => [
        `easing${pascalCase(curve)}`,
        `'${cubicBezierAt(allTokens, curve)}'`,
      ],
    ),
  ]
}

/** @param {TransformedToken[]} allTokens @returns {Entry[]} */
function stateLayerOpacityEntries(allTokens) {
  const keys = [
    'hover',
    'focus',
    'pressed',
    'dragged',
    'disabledContainer',
    'disabledContent',
  ]
  return keys.map((key) => [
    key,
    `'${byPath(allTokens, 'stateLayerOpacity', key)}'`,
  ])
}

// Window size classes, smallest first — see layout.breakpoint in
// design.tokens.json.
const BREAKPOINTS = ['compact', 'medium', 'expanded', 'large', 'extraLarge']

/** @param {TransformedToken[]} allTokens @param {string} key @returns {string} */
function breakpointAt(allTokens, key) {
  /** @type {unknown} */
  const value = byPath(allTokens, 'layout', 'breakpoint', key)
  if (typeof value !== 'string') {
    throw new TypeError(`Expected string for layout.breakpoint.${key}`)
  }
  return value
}

/** @param {TransformedToken[]} allTokens @returns {Entry[]} */
function breakpointEntries(allTokens) {
  return BREAKPOINTS.map((key) => [key, `'${breakpointAt(allTokens, key)}'`])
}

// A ready-made at-rule per class in both directions, since a media query
// written by hand from a raw breakpoint is the step where the off-by-one
// creeps in: the classic max-width pairing for a 600px floor is 599.98px,
// and getting it wrong leaves a one-pixel window matching both queries or
// neither. Range syntax sidesteps that arithmetic entirely — `< 600px` and
// `>= 600px` partition the axis exactly, with no fractional fudge.
//
// `medium` is the up-query and `belowMedium` its complement, rather than a
// Bootstrap-style medium/mediumDown pair where `down` silently means "below
// the *next* class up". compact appears in neither: `width >= 0px` is always
// true and `width < 0px` never is, so its two queries would be a no-op and a
// dead rule. It is the base every style starts from, not a query.
/** @param {TransformedToken[]} allTokens @returns {Entry[]} */
function mediaEntries(allTokens) {
  /** @type {Entry[]} */
  const entries = []
  for (const key of BREAKPOINTS.slice(1)) {
    const width = breakpointAt(allTokens, key)
    entries.push([key, `'@media (width >= ${width})'`])
    entries.push([`below${pascalCase(key)}`, `'@media (width < ${width})'`])
  }
  return entries
}

/** @param {unknown} value @returns {value is import('oxfmt').FormatConfig} */
function isPlainObject(value) {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

// oxfmt's format() doesn't read .oxfmtrc.json for programmatic callers — it
// only auto-discovers config for its CLI — so the repo's config is loaded
// and passed explicitly to keep generated output consistent with `npm run
// format`. The $schema key oxfmt itself doesn't declare is harmless to pass
// through — confirmed it's silently ignored, same as any other unknown key.
/** @type {unknown} */
const parsedOxfmtConfig = JSON.parse(
  readFileSync(new URL('../.oxfmtrc.json', import.meta.url), 'utf8'),
)
if (!isPlainObject(parsedOxfmtConfig)) {
  throw new TypeError('.oxfmtrc.json must contain a JSON object')
}
const oxfmtConfig = parsedOxfmtConfig

// `filename` only has to carry the right extension — oxfmt dispatches its
// formatting mode off of it (confirmed: passing a .css name formats as
// CSS), it doesn't need to be a real path.
/** @param {string} filename @param {string} source @returns {Promise<string>} */
async function prettify(filename, source) {
  const { code, errors } = await oxfmtFormat(filename, source, oxfmtConfig)
  if (errors.length > 0) {
    throw new Error(
      `oxfmt failed to format generated ${filename}: ${errors.map((e) => e.message).join('; ')}`,
    )
  }
  return code
}

/** @param {TransformedToken[]} allTokens @returns {string} */
function stylexSource(allTokens) {
  const themedEntries = colorThemedEntries(allTokens)
  return `${STYLEX_BANNER}import * as stylex from '@stylexjs/stylex'

const DARK = '@media (prefers-color-scheme: dark)'

${themedVarsBlock('colors', themedEntries)}

${themeOverrideBlocks('colors', themedEntries)}

${defineVarsBlock(
  'typography',
  withCssVarFallback('typography', typographyEntries(allTokens)),
)}

${defineVarsBlock('spacing', withCssVarFallback('spacing', spacingEntries(allTokens)))}

${defineVarsBlock('radii', withCssVarFallback('radii', radiiEntries(allTokens)))}

${defineVarsBlock(
  'shadows',
  withCssVarFallback('shadows', shadowsEntries(allTokens)),
)}

${defineVarsBlock(
  'stateLayerOpacity',
  withCssVarFallback('stateLayerOpacity', stateLayerOpacityEntries(allTokens)),
)}

${defineVarsBlock('motion', withCssVarFallback('motion', motionEntries(allTokens)))}

${defineConstsBlock('breakpoints', breakpointEntries(allTokens))}

${defineConstsBlock('media', mediaEntries(allTokens))}
`
}

/** @param {string} group @param {Entry[]} entries @returns {string[]} */
function cssLines(group, entries) {
  return entries.map(
    ([key, value]) =>
      `  ${cssVarName(group, key)}: ${unquoteJsStringLiteral(value)};`,
  )
}

// layout.breakpoint is absent by design, not by oversight: a custom property
// here would advertise an override that cannot work, since the media queries
// consuming it are compiled to literals and no var() in a condition would be
// read. Retheming a breakpoint means editing design.tokens.json and
// rebuilding, which is the honest story for a value the compiler has to bake
// in — everything else in this file really is overridable at runtime.
/** @param {TransformedToken[]} allTokens @returns {string} */
function cssSource(allTokens) {
  const themedEntries = colorThemedEntries(allTokens)
  const rootLines = [
    ...themedEntries.map(
      ([key, light]) => `  ${cssVarName('colors', key)}: ${light};`,
    ),
    ...cssLines('typography', typographyEntries(allTokens)),
    ...cssLines('spacing', spacingEntries(allTokens)),
    ...cssLines('radii', radiiEntries(allTokens)),
    ...cssLines('shadows', shadowsEntries(allTokens)),
    ...cssLines('stateLayerOpacity', stateLayerOpacityEntries(allTokens)),
    ...cssLines('motion', motionEntries(allTokens)),
  ].toSorted((a, b) => a.trim().localeCompare(b.trim()))
  const darkLines = themedEntries
    .map(([key, , dark]) => `    ${cssVarName('colors', key)}: ${dark};`)
    .toSorted((a, b) => a.trim().localeCompare(b.trim()))
  return `${CSS_BANNER}:root {
${rootLines.join('\n')}
}

@media (prefers-color-scheme: dark) {
  :root {
${darkLines.join('\n')}
  }
}
`
}

// Registers the stylex/design-tokens and css/design-tokens formats.
// Exported (alongside styleDictionaryConfig below) so vite.config.ts and
// tsdown.config.ts can drive the exact same build through
// unplugin-style-dictionary's `config: () => {...}` option, instead of
// duplicating this logic — see their `config` functions for the other half
// of that wiring. Style Dictionary silently replaces a format re-registered
// under the same name, so calling this more than once per process (e.g.
// once per rebuild during `storybook dev`) is safe.
export function registerFormats() {
  StyleDictionary.registerFormat({
    /** @param {import('style-dictionary/types').FormatFnArguments} args */
    format: async ({ dictionary }) =>
      prettify('design.tokens.stylex.ts', stylexSource(dictionary.allTokens)),
    name: 'stylex/design-tokens',
  })
  StyleDictionary.registerFormat({
    /** @param {import('style-dictionary/types').FormatFnArguments} args */
    format: async ({ dictionary }) =>
      prettify('design.tokens.css', cssSource(dictionary.allTokens)),
    name: 'css/design-tokens',
  })
}

export const styleDictionaryConfig = {
  platforms: {
    css: {
      buildPath: 'src/tokens/',
      // See the `stylex` platform below for why this transform is here —
      // the same reasoning applies, since this format also keys off
      // `token.path` exclusively.
      transforms: ['name/kebab'],
      files: [
        {
          destination: 'design.tokens.css',
          format: 'css/design-tokens',
        },
      ],
    },
    stylex: {
      buildPath: 'src/tokens/',
      // The formats above key off `token.path`, not `token.name` — this
      // transform just gives every token a unique full-path name so Style
      // Dictionary's collision diagnostics (aimed at flat-name formats)
      // don't fire spuriously.
      transforms: ['name/kebab'],
      files: [
        {
          destination: 'design.tokens.stylex.ts',
          format: 'stylex/design-tokens',
        },
      ],
    },
  },
  source: ['src/tokens/*.tokens.json'],
  usesDtcg: true,
}

// CLI entry point (`npm run tokens:build`) — a one-shot regenerate outside
// of any bundler, e.g. to inspect the diff after editing design.tokens.json,
// or a CI check that generated output is up to date. vite.config.ts and
// tsdown.config.ts import registerFormats/styleDictionaryConfig directly
// instead of shelling out to this, so tokens are regenerated automatically
// as part of storybook dev/build, vitest, and the tsdown package build too —
// this script is no longer the only way it happens, just the manual one.
if (import.meta.main) {
  registerFormats()
  const sd = new StyleDictionary(styleDictionaryConfig)
  await sd.buildAllPlatforms()
}
