#!/usr/bin/env node
// Generates src/tokens/design.tokens.stylex.ts from the W3C Design Tokens
// (DTCG) source in src/tokens/design.tokens.json, via Style Dictionary.
// design.tokens.stylex.ts is committed output, not built at install time.
// The .stylex.ts suffix is required, not stylistic: @stylexjs/babel-plugin's
// cross-file variable resolution only recognizes theme files whose name ends
// in .stylex.ts/.stylex.js (unstable_moduleResolution.themeFileExtension,
// defaults to '.stylex') — a plain design.tokens.ts fails to build.
//
// Dual-purpose: run directly (`npm run tokens:build`) for a one-shot
// regenerate, or import registerFormats/styleDictionaryConfig from
// vite.config.ts / tsdown.config.ts to drive the same build automatically
// via unplugin-style-dictionary — see the CLI guard at the bottom.
import { readFileSync } from 'node:fs'

import { format as oxfmtFormat } from 'oxfmt'
import StyleDictionary from 'style-dictionary'

/**
 * @typedef {import('style-dictionary/types').TransformedToken} TransformedToken
 * @typedef {[name: string, light: string, dark: string]} ThemedEntry
 * @typedef {{ offsetX: string, offsetY: string, blur: string, spread: string, color: string }} ShadowLayer
 */

const BANNER = `// AUTO-GENERATED by scripts/build-tokens.mjs from the sibling design.tokens.json.
// Do not hand-edit — change design.tokens.json and run \`npm run tokens:build\`.
// The .stylex.ts suffix is required by @stylexjs/babel-plugin for cross-file
// variable resolution — see the comment at the top of build-tokens.mjs.

`

/** @param {string} key @returns {string} */
function pascalCase(key) {
  return key.charAt(0).toUpperCase() + key.slice(1)
}

/** @param {string} fontName @returns {string} */
function quoteIfNeeded(fontName) {
  return fontName.includes(' ') ? `'${fontName}'` : fontName
}

// $value is typed `any` by style-dictionary itself (a DTCG token's value is
// polymorphic depending on $type), so callers that need more than a plain
// string narrow the result through one of the type guards below.
/** @param {TransformedToken[]} allTokens @param {...string} path @returns {any} */
function byPath(allTokens, ...path) {
  const joined = path.join('.')
  const token = allTokens.find((t) => t.path.join('.') === joined)
  if (!token) throw new Error(`Missing token: {${joined}}`)
  return token.$value
}

/** @param {unknown} value @returns {value is string[]} */
function isStringArray(value) {
  return Array.isArray(value) && value.every((v) => typeof v === 'string')
}

/** @param {unknown} value @returns {value is ShadowLayer} */
function isShadowLayer(value) {
  return (
    typeof value === 'object' &&
    value !== null &&
    'offsetX' in value &&
    typeof value.offsetX === 'string' &&
    'offsetY' in value &&
    typeof value.offsetY === 'string' &&
    'blur' in value &&
    typeof value.blur === 'string' &&
    'spread' in value &&
    typeof value.spread === 'string' &&
    'color' in value &&
    typeof value.color === 'string'
  )
}

/** @param {unknown} value @returns {value is ShadowLayer[]} */
function isShadowLayerArray(value) {
  return Array.isArray(value) && value.every(isShadowLayer)
}

/** @param {string} exportName @param {[string, string][]} entries @returns {string} */
function defineVarsBlock(exportName, entries) {
  const lines = entries
    .map(([name, value]) => `  ${name}: ${value},`)
    .toSorted((a, b) => a.trim().localeCompare(b.trim()))
  return `const ${exportName} = stylex.defineVars({
${lines.join('\n')}
})

export { ${exportName} }`
}

/** @param {string} exportName @param {ThemedEntry[]} entries @returns {string} */
function themedVarsBlock(exportName, entries) {
  const lines = entries
    .map(
      ([name, light, dark]) =>
        `  ${name}: { [DARK]: '${dark}', default: '${light}' },`,
    )
    .toSorted((a, b) => a.trim().localeCompare(b.trim()))
  return `const ${exportName} = stylex.defineVars({
${lines.join('\n')}
})

export { ${exportName} }`
}

// A stylex.createTheme() pair per themed var group: overrideable classes
// that pin every var to an explicit light or dark value, regardless of the
// OS-level prefers-color-scheme media query the vars above default to. A
// manual toggle (Storybook's dark-mode addon, or any future in-app theme
// switcher) needs both directions — forcing dark isn't enough on its own,
// since forcing *light* against a dark OS preference is exactly as common a
// case and would otherwise silently fall through to the media query.
/** @param {string} exportName @param {ThemedEntry[]} entries @returns {string} */
function themeOverrideBlocks(exportName, entries) {
  /** @param {'light' | 'dark'} mode @param {0 | 1} valueIndex @returns {string} */
  const build = (mode, valueIndex) => {
    const lines = entries
      .map(([name, ...values]) => `  ${name}: '${values[valueIndex]}',`)
      .toSorted((a, b) => a.trim().localeCompare(b.trim()))
    const themeExportName = `${exportName}${pascalCase(mode)}Theme`
    return `const ${themeExportName} = stylex.createTheme(${exportName}, {
${lines.join('\n')}
})

export { ${themeExportName} }`
  }
  return `${build('light', 0)}

${build('dark', 1)}`
}

/** @param {ShadowLayer[]} layers @returns {string} */
function serializeShadowLayers(layers) {
  return layers
    .map((l) => `${l.offsetX} ${l.offsetY} ${l.blur} ${l.spread} ${l.color}`)
    .join(', ')
}

/** @param {TransformedToken[]} allTokens @returns {string} */
function colorsBlock(allTokens) {
  const keys = [
    ...new Set(
      allTokens
        .filter((t) => t.path[0] === 'semantic' && t.path[1] === 'light')
        .map((t) => t.path[2]),
    ),
  ]
  /** @type {ThemedEntry[]} */
  const entries = keys.map((key) => [
    key,
    byPath(allTokens, 'semantic', 'light', key),
    byPath(allTokens, 'semantic', 'dark', key),
  ])
  return `${themedVarsBlock('colors', entries)}

${themeOverrideBlocks('colors', entries)}`
}

// The full 15-style type scale (display/headline/title/body/label ×
// large/medium/small) — see typography.scale in design.tokens.json.
const SCALE_STYLES = [
  'displayLarge',
  'displayMedium',
  'displaySmall',
  'headlineLarge',
  'headlineMedium',
  'headlineSmall',
  'titleLarge',
  'titleMedium',
  'titleSmall',
  'bodyLarge',
  'bodyMedium',
  'bodySmall',
  'labelLarge',
  'labelMedium',
  'labelSmall',
]

/** @param {TransformedToken[]} allTokens @returns {string} */
function typographyBlock(allTokens) {
  /** @type {[string, string][]} */
  const entries = []
  for (const key of ['brand', 'plain', 'mono']) {
    /** @type {unknown} */
    const value = byPath(allTokens, 'typography', 'fontFamily', key)
    if (!isStringArray(value)) {
      throw new TypeError(`Expected string[] for typography.fontFamily.${key}`)
    }
    entries.push([
      `fontFamily${pascalCase(key)}`,
      `"${value.map(quoteIfNeeded).join(', ')}"`,
    ])
  }
  for (const key of ['regular', 'medium', 'bold']) {
    entries.push([
      `weight${pascalCase(key)}`,
      `'${byPath(allTokens, 'typography', 'fontWeight', key)}'`,
    ])
  }
  for (const style of SCALE_STYLES) {
    /** @type {unknown} */
    const font = byPath(allTokens, 'typography', 'scale', style, 'font')
    if (!isStringArray(font)) {
      throw new TypeError(
        `Expected string[] for typography.scale.${style}.font`,
      )
    }
    entries.push([`${style}Font`, `"${font.map(quoteIfNeeded).join(', ')}"`])
    for (const field of ['size', 'lineHeight', 'tracking', 'weight']) {
      entries.push([
        `${style}${pascalCase(field)}`,
        `'${byPath(allTokens, 'typography', 'scale', style, field)}'`,
      ])
    }
  }
  return defineVarsBlock('typography', entries)
}

/** @param {TransformedToken[]} allTokens @returns {string} */
function spacingBlock(allTokens) {
  const keys = ['xxs', 'xs', 'sm', 'md', 'lg', 'xl', 'xxl', 'xxxl']
  /** @type {[string, string][]} */
  const entries = keys.map((key) => [
    key,
    `'${byPath(allTokens, 'spacing', 'component', key)}'`,
  ])
  return defineVarsBlock('spacing', entries)
}

/** @param {TransformedToken[]} allTokens @returns {string} */
function radiiBlock(allTokens) {
  const keys = ['none', 'xs', 'sm', 'md', 'lg', 'xl', 'full']
  /** @type {[string, string][]} */
  const entries = keys.map((key) => [
    key,
    `'${byPath(allTokens, 'radii', 'component', key)}'`,
  ])
  return defineVarsBlock('radii', entries)
}

// Elevation shadows render as a fixed black in both light and dark schemes
// — dark mode instead conveys elevation via the surface-container tones in
// semantic.*, not a shadow-opacity shift. So unlike colors, shadows need no
// light/dark split.
/** @param {TransformedToken[]} allTokens @param {string} level @returns {string} */
function shadowLayersAt(allTokens, level) {
  /** @type {unknown} */
  const value = byPath(allTokens, 'shadow', level)
  if (!isShadowLayerArray(value)) {
    throw new TypeError(`Expected ShadowLayer[] for shadow.${level}`)
  }
  return serializeShadowLayers(value)
}

/** @param {TransformedToken[]} allTokens @returns {string} */
function shadowsBlock(allTokens) {
  /** @type {[string, string][]} */
  const entries = ['1', '2', '3', '4', '5'].map((level) => [
    `elevation${level}`,
    `'${shadowLayersAt(allTokens, level)}'`,
  ])
  return defineVarsBlock('shadows', entries)
}

/** @param {TransformedToken[]} allTokens @returns {string} */
function stateLayerOpacityBlock(allTokens) {
  const keys = [
    'hover',
    'focus',
    'pressed',
    'dragged',
    'disabledContainer',
    'disabledContent',
  ]
  /** @type {[string, string][]} */
  const entries = keys.map((key) => [
    key,
    `'${byPath(allTokens, 'stateLayerOpacity', key)}'`,
  ])
  return defineVarsBlock('stateLayerOpacity', entries)
}

/** @param {unknown} value @returns {value is import('oxfmt').FormatConfig} */
function isPlainObject(value) {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

// oxfmt's format() doesn't read .oxfmtrc.json for programmatic callers — it
// only auto-discovers config for its CLI — so the repo's config is loaded
// and passed explicitly to keep generated output consistent with `npm run
// format`. The $schema key oxfmt itself doesn't declare is harmless to pass
// through — confirmed it's silently ignored, same as any other unknown key.
/** @type {unknown} */
const parsedOxfmtConfig = JSON.parse(
  readFileSync(new URL('../.oxfmtrc.json', import.meta.url), 'utf8'),
)
if (!isPlainObject(parsedOxfmtConfig)) {
  throw new TypeError('.oxfmtrc.json must contain a JSON object')
}
const oxfmtConfig = parsedOxfmtConfig

/** @param {string} source @returns {Promise<string>} */
async function prettify(source) {
  const { code, errors } = await oxfmtFormat(
    'design.tokens.stylex.ts',
    source,
    oxfmtConfig,
  )
  if (errors.length > 0) {
    throw new Error(
      `oxfmt failed to format generated output: ${errors.map((e) => e.message).join('; ')}`,
    )
  }
  return code
}

// Registers the stylex/design-tokens format. Exported (alongside
// styleDictionaryConfig below) so vite.config.ts and tsdown.config.ts can
// drive the exact same build through unplugin-style-dictionary's
// `config: () => {...}` option, instead of duplicating this logic — see
// their `config` functions for the other half of that wiring. Style
// Dictionary silently replaces a format re-registered under the same name,
// so calling this more than once per process (e.g. once per rebuild during
// `storybook dev`) is safe.
export function registerFormats() {
  StyleDictionary.registerFormat({
    /** @param {import('style-dictionary/types').FormatFnArguments} args */
    format: async ({ dictionary }) => {
      const { allTokens } = dictionary
      const source = `${BANNER}import * as stylex from '@stylexjs/stylex'

const DARK = '@media (prefers-color-scheme: dark)'

${colorsBlock(allTokens)}

${typographyBlock(allTokens)}

${spacingBlock(allTokens)}

${radiiBlock(allTokens)}

${shadowsBlock(allTokens)}

${stateLayerOpacityBlock(allTokens)}
`
      return prettify(source)
    },
    name: 'stylex/design-tokens',
  })
}

export const styleDictionaryConfig = {
  platforms: {
    stylex: {
      buildPath: 'src/tokens/',
      // The format above keys off `token.path`, not `token.name` — this
      // transform just gives every token a unique full-path name so Style
      // Dictionary's collision diagnostics (aimed at flat-name formats)
      // don't fire spuriously.
      transforms: ['name/kebab'],
      files: [
        {
          destination: 'design.tokens.stylex.ts',
          format: 'stylex/design-tokens',
        },
      ],
    },
  },
  source: ['src/tokens/*.tokens.json'],
  usesDtcg: true,
}

// CLI entry point (`npm run tokens:build`) — a one-shot regenerate outside
// of any bundler, e.g. to inspect the diff after editing design.tokens.json,
// or a CI check that generated output is up to date. vite.config.ts and
// tsdown.config.ts import registerFormats/styleDictionaryConfig directly
// instead of shelling out to this, so tokens are regenerated automatically
// as part of storybook dev/build, vitest, and the tsdown package build too —
// this script is no longer the only way it happens, just the manual one.
if (import.meta.main) {
  registerFormats()
  const sd = new StyleDictionary(styleDictionaryConfig)
  await sd.buildAllPlatforms()
}
