// AUTO-GENERATED by scripts/build-tokens.mjs from the sibling design.tokens.json.
// Do not hand-edit — change design.tokens.json and run `npm run tokens:build`.
// The .stylex.ts suffix is required by @stylexjs/babel-plugin for cross-file
// variable resolution — see the comment at the top of build-tokens.mjs.

import * as stylex from '@stylexjs/stylex'

const DARK = '@media (prefers-color-scheme: dark)'

const colorDefaults = stylex.defineVars({
  background: { [DARK]: '#141218', default: '#fef7ff' },
  error: { [DARK]: '#f2b8b5', default: '#b3261e' },
  errorContainer: { [DARK]: '#8c1d18', default: '#f9dedc' },
  inverseOnSurface: { [DARK]: '#322f35', default: '#f5eff7' },
  inversePrimary: { [DARK]: '#6750a4', default: '#d0bcff' },
  inverseSurface: { [DARK]: '#e6e0e9', default: '#322f35' },
  negative: { [DARK]: '#ffb59f', default: '#a04022' },
  negativeContainer: { [DARK]: '#81290c', default: '#ffdbd1' },
  onBackground: { [DARK]: '#e6e0e9', default: '#1d1b20' },
  onError: { [DARK]: '#601410', default: '#ffffff' },
  onErrorContainer: { [DARK]: '#f9dedc', default: '#410e0b' },
  onNegative: { [DARK]: '#5f1600', default: '#ffffff' },
  onNegativeContainer: { [DARK]: '#ffdbd1', default: '#3a0a00' },
  onPositive: { [DARK]: '#003827', default: '#ffffff' },
  onPositiveContainer: { [DARK]: '#90f6ca', default: '#002115' },
  onPrimary: { [DARK]: '#381e72', default: '#ffffff' },
  onPrimaryContainer: { [DARK]: '#eaddff', default: '#21005d' },
  onPrimaryFixed: { [DARK]: '#21005d', default: '#21005d' },
  onPrimaryFixedVariant: { [DARK]: '#4f378b', default: '#4f378b' },
  onSecondary: { [DARK]: '#332d41', default: '#ffffff' },
  onSecondaryContainer: { [DARK]: '#e8def8', default: '#1d192b' },
  onSecondaryFixed: { [DARK]: '#1d192b', default: '#1d192b' },
  onSecondaryFixedVariant: { [DARK]: '#4a4458', default: '#4a4458' },
  onSurface: { [DARK]: '#e6e0e9', default: '#1d1b20' },
  onSurfaceVariant: { [DARK]: '#cac4d0', default: '#49454f' },
  onTertiary: { [DARK]: '#492532', default: '#ffffff' },
  onTertiaryContainer: { [DARK]: '#ffd8e4', default: '#31111d' },
  onTertiaryFixed: { [DARK]: '#31111d', default: '#31111d' },
  onTertiaryFixedVariant: { [DARK]: '#633b48', default: '#633b48' },
  outline: { [DARK]: '#938f99', default: '#79747e' },
  outlineVariant: { [DARK]: '#49454f', default: '#cac4d0' },
  positive: { [DARK]: '#74d9af', default: '#006c4d' },
  positiveContainer: { [DARK]: '#00513a', default: '#90f6ca' },
  primary: { [DARK]: '#d0bcff', default: '#6750a4' },
  primaryContainer: { [DARK]: '#4f378b', default: '#eaddff' },
  primaryFixed: { [DARK]: '#eaddff', default: '#eaddff' },
  primaryFixedDim: { [DARK]: '#d0bcff', default: '#d0bcff' },
  scrim: { [DARK]: '#000000', default: '#000000' },
  secondary: { [DARK]: '#ccc2dc', default: '#625b71' },
  secondaryContainer: { [DARK]: '#4a4458', default: '#e8def8' },
  secondaryFixed: { [DARK]: '#e8def8', default: '#e8def8' },
  secondaryFixedDim: { [DARK]: '#ccc2dc', default: '#ccc2dc' },
  shadow: { [DARK]: '#000000', default: '#000000' },
  surface: { [DARK]: '#141218', default: '#fef7ff' },
  surfaceBright: { [DARK]: '#3b383e', default: '#fef7ff' },
  surfaceContainer: { [DARK]: '#211f26', default: '#f3edf7' },
  surfaceContainerHigh: { [DARK]: '#2b2930', default: '#ece6f0' },
  surfaceContainerHighest: { [DARK]: '#36343b', default: '#e6e0e9' },
  surfaceContainerLow: { [DARK]: '#1d1b20', default: '#f7f2fa' },
  surfaceContainerLowest: { [DARK]: '#0f0d13', default: '#ffffff' },
  surfaceDim: { [DARK]: '#141218', default: '#ded8e1' },
  surfaceTint: { [DARK]: '#d0bcff', default: '#6750a4' },
  surfaceVariant: { [DARK]: '#49454f', default: '#e7e0ec' },
  tertiary: { [DARK]: '#efb8c8', default: '#7d5260' },
  tertiaryContainer: { [DARK]: '#633b48', default: '#ffd8e4' },
  tertiaryFixed: { [DARK]: '#ffd8e4', default: '#ffd8e4' },
  tertiaryFixedDim: { [DARK]: '#efb8c8', default: '#efb8c8' },
})

export { colorDefaults }

const colors = stylex.defineVars({
  background: `var(--kui-color-background, ${colorDefaults.background})`,
  error: `var(--kui-color-error, ${colorDefaults.error})`,
  errorContainer: `var(--kui-color-error-container, ${colorDefaults.errorContainer})`,
  inverseOnSurface: `var(--kui-color-inverse-on-surface, ${colorDefaults.inverseOnSurface})`,
  inversePrimary: `var(--kui-color-inverse-primary, ${colorDefaults.inversePrimary})`,
  inverseSurface: `var(--kui-color-inverse-surface, ${colorDefaults.inverseSurface})`,
  negative: `var(--kui-color-negative, ${colorDefaults.negative})`,
  negativeContainer: `var(--kui-color-negative-container, ${colorDefaults.negativeContainer})`,
  onBackground: `var(--kui-color-on-background, ${colorDefaults.onBackground})`,
  onError: `var(--kui-color-on-error, ${colorDefaults.onError})`,
  onErrorContainer: `var(--kui-color-on-error-container, ${colorDefaults.onErrorContainer})`,
  onNegative: `var(--kui-color-on-negative, ${colorDefaults.onNegative})`,
  onNegativeContainer: `var(--kui-color-on-negative-container, ${colorDefaults.onNegativeContainer})`,
  onPositive: `var(--kui-color-on-positive, ${colorDefaults.onPositive})`,
  onPositiveContainer: `var(--kui-color-on-positive-container, ${colorDefaults.onPositiveContainer})`,
  onPrimary: `var(--kui-color-on-primary, ${colorDefaults.onPrimary})`,
  onPrimaryContainer: `var(--kui-color-on-primary-container, ${colorDefaults.onPrimaryContainer})`,
  onPrimaryFixed: `var(--kui-color-on-primary-fixed, ${colorDefaults.onPrimaryFixed})`,
  onPrimaryFixedVariant: `var(--kui-color-on-primary-fixed-variant, ${colorDefaults.onPrimaryFixedVariant})`,
  onSecondary: `var(--kui-color-on-secondary, ${colorDefaults.onSecondary})`,
  onSecondaryContainer: `var(--kui-color-on-secondary-container, ${colorDefaults.onSecondaryContainer})`,
  onSecondaryFixed: `var(--kui-color-on-secondary-fixed, ${colorDefaults.onSecondaryFixed})`,
  onSecondaryFixedVariant: `var(--kui-color-on-secondary-fixed-variant, ${colorDefaults.onSecondaryFixedVariant})`,
  onSurface: `var(--kui-color-on-surface, ${colorDefaults.onSurface})`,
  onSurfaceVariant: `var(--kui-color-on-surface-variant, ${colorDefaults.onSurfaceVariant})`,
  onTertiary: `var(--kui-color-on-tertiary, ${colorDefaults.onTertiary})`,
  onTertiaryContainer: `var(--kui-color-on-tertiary-container, ${colorDefaults.onTertiaryContainer})`,
  onTertiaryFixed: `var(--kui-color-on-tertiary-fixed, ${colorDefaults.onTertiaryFixed})`,
  onTertiaryFixedVariant: `var(--kui-color-on-tertiary-fixed-variant, ${colorDefaults.onTertiaryFixedVariant})`,
  outline: `var(--kui-color-outline, ${colorDefaults.outline})`,
  outlineVariant: `var(--kui-color-outline-variant, ${colorDefaults.outlineVariant})`,
  positive: `var(--kui-color-positive, ${colorDefaults.positive})`,
  positiveContainer: `var(--kui-color-positive-container, ${colorDefaults.positiveContainer})`,
  primary: `var(--kui-color-primary, ${colorDefaults.primary})`,
  primaryContainer: `var(--kui-color-primary-container, ${colorDefaults.primaryContainer})`,
  primaryFixed: `var(--kui-color-primary-fixed, ${colorDefaults.primaryFixed})`,
  primaryFixedDim: `var(--kui-color-primary-fixed-dim, ${colorDefaults.primaryFixedDim})`,
  scrim: `var(--kui-color-scrim, ${colorDefaults.scrim})`,
  secondary: `var(--kui-color-secondary, ${colorDefaults.secondary})`,
  secondaryContainer: `var(--kui-color-secondary-container, ${colorDefaults.secondaryContainer})`,
  secondaryFixed: `var(--kui-color-secondary-fixed, ${colorDefaults.secondaryFixed})`,
  secondaryFixedDim: `var(--kui-color-secondary-fixed-dim, ${colorDefaults.secondaryFixedDim})`,
  shadow: `var(--kui-color-shadow, ${colorDefaults.shadow})`,
  surface: `var(--kui-color-surface, ${colorDefaults.surface})`,
  surfaceBright: `var(--kui-color-surface-bright, ${colorDefaults.surfaceBright})`,
  surfaceContainer: `var(--kui-color-surface-container, ${colorDefaults.surfaceContainer})`,
  surfaceContainerHigh: `var(--kui-color-surface-container-high, ${colorDefaults.surfaceContainerHigh})`,
  surfaceContainerHighest: `var(--kui-color-surface-container-highest, ${colorDefaults.surfaceContainerHighest})`,
  surfaceContainerLow: `var(--kui-color-surface-container-low, ${colorDefaults.surfaceContainerLow})`,
  surfaceContainerLowest: `var(--kui-color-surface-container-lowest, ${colorDefaults.surfaceContainerLowest})`,
  surfaceDim: `var(--kui-color-surface-dim, ${colorDefaults.surfaceDim})`,
  surfaceTint: `var(--kui-color-surface-tint, ${colorDefaults.surfaceTint})`,
  surfaceVariant: `var(--kui-color-surface-variant, ${colorDefaults.surfaceVariant})`,
  tertiary: `var(--kui-color-tertiary, ${colorDefaults.tertiary})`,
  tertiaryContainer: `var(--kui-color-tertiary-container, ${colorDefaults.tertiaryContainer})`,
  tertiaryFixed: `var(--kui-color-tertiary-fixed, ${colorDefaults.tertiaryFixed})`,
  tertiaryFixedDim: `var(--kui-color-tertiary-fixed-dim, ${colorDefaults.tertiaryFixedDim})`,
})

export { colors }

const colorDefaultsLightTheme = stylex.createTheme(colorDefaults, {
  background: '#fef7ff',
  error: '#b3261e',
  errorContainer: '#f9dedc',
  inverseOnSurface: '#f5eff7',
  inversePrimary: '#d0bcff',
  inverseSurface: '#322f35',
  negative: '#a04022',
  negativeContainer: '#ffdbd1',
  onBackground: '#1d1b20',
  onError: '#ffffff',
  onErrorContainer: '#410e0b',
  onNegative: '#ffffff',
  onNegativeContainer: '#3a0a00',
  onPositive: '#ffffff',
  onPositiveContainer: '#002115',
  onPrimary: '#ffffff',
  onPrimaryContainer: '#21005d',
  onPrimaryFixed: '#21005d',
  onPrimaryFixedVariant: '#4f378b',
  onSecondary: '#ffffff',
  onSecondaryContainer: '#1d192b',
  onSecondaryFixed: '#1d192b',
  onSecondaryFixedVariant: '#4a4458',
  onSurface: '#1d1b20',
  onSurfaceVariant: '#49454f',
  onTertiary: '#ffffff',
  onTertiaryContainer: '#31111d',
  onTertiaryFixed: '#31111d',
  onTertiaryFixedVariant: '#633b48',
  outline: '#79747e',
  outlineVariant: '#cac4d0',
  positive: '#006c4d',
  positiveContainer: '#90f6ca',
  primary: '#6750a4',
  primaryContainer: '#eaddff',
  primaryFixed: '#eaddff',
  primaryFixedDim: '#d0bcff',
  scrim: '#000000',
  secondary: '#625b71',
  secondaryContainer: '#e8def8',
  secondaryFixed: '#e8def8',
  secondaryFixedDim: '#ccc2dc',
  shadow: '#000000',
  surface: '#fef7ff',
  surfaceBright: '#fef7ff',
  surfaceContainer: '#f3edf7',
  surfaceContainerHigh: '#ece6f0',
  surfaceContainerHighest: '#e6e0e9',
  surfaceContainerLow: '#f7f2fa',
  surfaceContainerLowest: '#ffffff',
  surfaceDim: '#ded8e1',
  surfaceTint: '#6750a4',
  surfaceVariant: '#e7e0ec',
  tertiary: '#7d5260',
  tertiaryContainer: '#ffd8e4',
  tertiaryFixed: '#ffd8e4',
  tertiaryFixedDim: '#efb8c8',
})

export { colorDefaultsLightTheme }

const colorDefaultsDarkTheme = stylex.createTheme(colorDefaults, {
  background: '#141218',
  error: '#f2b8b5',
  errorContainer: '#8c1d18',
  inverseOnSurface: '#322f35',
  inversePrimary: '#6750a4',
  inverseSurface: '#e6e0e9',
  negative: '#ffb59f',
  negativeContainer: '#81290c',
  onBackground: '#e6e0e9',
  onError: '#601410',
  onErrorContainer: '#f9dedc',
  onNegative: '#5f1600',
  onNegativeContainer: '#ffdbd1',
  onPositive: '#003827',
  onPositiveContainer: '#90f6ca',
  onPrimary: '#381e72',
  onPrimaryContainer: '#eaddff',
  onPrimaryFixed: '#21005d',
  onPrimaryFixedVariant: '#4f378b',
  onSecondary: '#332d41',
  onSecondaryContainer: '#e8def8',
  onSecondaryFixed: '#1d192b',
  onSecondaryFixedVariant: '#4a4458',
  onSurface: '#e6e0e9',
  onSurfaceVariant: '#cac4d0',
  onTertiary: '#492532',
  onTertiaryContainer: '#ffd8e4',
  onTertiaryFixed: '#31111d',
  onTertiaryFixedVariant: '#633b48',
  outline: '#938f99',
  outlineVariant: '#49454f',
  positive: '#74d9af',
  positiveContainer: '#00513a',
  primary: '#d0bcff',
  primaryContainer: '#4f378b',
  primaryFixed: '#eaddff',
  primaryFixedDim: '#d0bcff',
  scrim: '#000000',
  secondary: '#ccc2dc',
  secondaryContainer: '#4a4458',
  secondaryFixed: '#e8def8',
  secondaryFixedDim: '#ccc2dc',
  shadow: '#000000',
  surface: '#141218',
  surfaceBright: '#3b383e',
  surfaceContainer: '#211f26',
  surfaceContainerHigh: '#2b2930',
  surfaceContainerHighest: '#36343b',
  surfaceContainerLow: '#1d1b20',
  surfaceContainerLowest: '#0f0d13',
  surfaceDim: '#141218',
  surfaceTint: '#d0bcff',
  surfaceVariant: '#49454f',
  tertiary: '#efb8c8',
  tertiaryContainer: '#633b48',
  tertiaryFixed: '#ffd8e4',
  tertiaryFixedDim: '#efb8c8',
})

export { colorDefaultsDarkTheme }

const typography = stylex.defineVars({
  bodyLargeFont:
    "var(--kui-typography-body-large-font, var(--kui-typography-font-family-plain, 'Roboto Flex', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif))",
  bodyLargeLineHeight: 'var(--kui-typography-body-large-line-height, 24px)',
  bodyLargeSize: 'var(--kui-typography-body-large-size, 16px)',
  bodyLargeTracking: 'var(--kui-typography-body-large-tracking, 0.5px)',
  bodyLargeWeight:
    'var(--kui-typography-body-large-weight, var(--kui-typography-weight-regular, 400))',
  bodyMediumFont:
    "var(--kui-typography-body-medium-font, var(--kui-typography-font-family-plain, 'Roboto Flex', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif))",
  bodyMediumLineHeight: 'var(--kui-typography-body-medium-line-height, 20px)',
  bodyMediumSize: 'var(--kui-typography-body-medium-size, 14px)',
  bodyMediumTracking: 'var(--kui-typography-body-medium-tracking, 0.25px)',
  bodyMediumWeight:
    'var(--kui-typography-body-medium-weight, var(--kui-typography-weight-regular, 400))',
  bodySmallFont:
    "var(--kui-typography-body-small-font, var(--kui-typography-font-family-plain, 'Roboto Flex', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif))",
  bodySmallLineHeight: 'var(--kui-typography-body-small-line-height, 16px)',
  bodySmallSize: 'var(--kui-typography-body-small-size, 12px)',
  bodySmallTracking: 'var(--kui-typography-body-small-tracking, 0.4px)',
  bodySmallWeight:
    'var(--kui-typography-body-small-weight, var(--kui-typography-weight-regular, 400))',
  displayLargeFont:
    "var(--kui-typography-display-large-font, var(--kui-typography-font-family-brand, 'Roboto Serif', 'Iowan Old Style', Georgia, serif))",
  displayLargeLineHeight:
    'var(--kui-typography-display-large-line-height, 64px)',
  displayLargeSize: 'var(--kui-typography-display-large-size, 57px)',
  displayLargeTracking: 'var(--kui-typography-display-large-tracking, -0.25px)',
  displayLargeWeight:
    'var(--kui-typography-display-large-weight, var(--kui-typography-weight-regular, 400))',
  displayMediumFont:
    "var(--kui-typography-display-medium-font, var(--kui-typography-font-family-brand, 'Roboto Serif', 'Iowan Old Style', Georgia, serif))",
  displayMediumLineHeight:
    'var(--kui-typography-display-medium-line-height, 52px)',
  displayMediumSize: 'var(--kui-typography-display-medium-size, 45px)',
  displayMediumTracking: 'var(--kui-typography-display-medium-tracking, 0px)',
  displayMediumWeight:
    'var(--kui-typography-display-medium-weight, var(--kui-typography-weight-regular, 400))',
  displaySmallFont:
    "var(--kui-typography-display-small-font, var(--kui-typography-font-family-brand, 'Roboto Serif', 'Iowan Old Style', Georgia, serif))",
  displaySmallLineHeight:
    'var(--kui-typography-display-small-line-height, 44px)',
  displaySmallSize: 'var(--kui-typography-display-small-size, 36px)',
  displaySmallTracking: 'var(--kui-typography-display-small-tracking, 0px)',
  displaySmallWeight:
    'var(--kui-typography-display-small-weight, var(--kui-typography-weight-regular, 400))',
  fontFamilyBrand:
    "var(--kui-typography-font-family-brand, 'Roboto Serif', 'Iowan Old Style', Georgia, serif)",
  fontFamilyMono:
    "var(--kui-typography-font-family-mono, 'Roboto Mono', ui-monospace, 'SF Mono', Menlo, monospace)",
  fontFamilyPlain:
    "var(--kui-typography-font-family-plain, 'Roboto Flex', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif)",
  headlineLargeFont:
    "var(--kui-typography-headline-large-font, var(--kui-typography-font-family-brand, 'Roboto Serif', 'Iowan Old Style', Georgia, serif))",
  headlineLargeLineHeight:
    'var(--kui-typography-headline-large-line-height, 40px)',
  headlineLargeSize: 'var(--kui-typography-headline-large-size, 32px)',
  headlineLargeTracking: 'var(--kui-typography-headline-large-tracking, 0px)',
  headlineLargeWeight:
    'var(--kui-typography-headline-large-weight, var(--kui-typography-weight-regular, 400))',
  headlineMediumFont:
    "var(--kui-typography-headline-medium-font, var(--kui-typography-font-family-brand, 'Roboto Serif', 'Iowan Old Style', Georgia, serif))",
  headlineMediumLineHeight:
    'var(--kui-typography-headline-medium-line-height, 36px)',
  headlineMediumSize: 'var(--kui-typography-headline-medium-size, 28px)',
  headlineMediumTracking: 'var(--kui-typography-headline-medium-tracking, 0px)',
  headlineMediumWeight:
    'var(--kui-typography-headline-medium-weight, var(--kui-typography-weight-regular, 400))',
  headlineSmallFont:
    "var(--kui-typography-headline-small-font, var(--kui-typography-font-family-brand, 'Roboto Serif', 'Iowan Old Style', Georgia, serif))",
  headlineSmallLineHeight:
    'var(--kui-typography-headline-small-line-height, 32px)',
  headlineSmallSize: 'var(--kui-typography-headline-small-size, 24px)',
  headlineSmallTracking: 'var(--kui-typography-headline-small-tracking, 0px)',
  headlineSmallWeight:
    'var(--kui-typography-headline-small-weight, var(--kui-typography-weight-regular, 400))',
  labelLargeFont:
    "var(--kui-typography-label-large-font, var(--kui-typography-font-family-plain, 'Roboto Flex', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif))",
  labelLargeLineHeight: 'var(--kui-typography-label-large-line-height, 20px)',
  labelLargeSize: 'var(--kui-typography-label-large-size, 14px)',
  labelLargeTracking: 'var(--kui-typography-label-large-tracking, 0.1px)',
  labelLargeWeight:
    'var(--kui-typography-label-large-weight, var(--kui-typography-weight-medium, 500))',
  labelMediumFont:
    "var(--kui-typography-label-medium-font, var(--kui-typography-font-family-plain, 'Roboto Flex', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif))",
  labelMediumLineHeight: 'var(--kui-typography-label-medium-line-height, 16px)',
  labelMediumSize: 'var(--kui-typography-label-medium-size, 12px)',
  labelMediumTracking: 'var(--kui-typography-label-medium-tracking, 0.5px)',
  labelMediumWeight:
    'var(--kui-typography-label-medium-weight, var(--kui-typography-weight-medium, 500))',
  labelSmallFont:
    "var(--kui-typography-label-small-font, var(--kui-typography-font-family-plain, 'Roboto Flex', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif))",
  labelSmallLineHeight: 'var(--kui-typography-label-small-line-height, 16px)',
  labelSmallSize: 'var(--kui-typography-label-small-size, 11px)',
  labelSmallTracking: 'var(--kui-typography-label-small-tracking, 0.5px)',
  labelSmallWeight:
    'var(--kui-typography-label-small-weight, var(--kui-typography-weight-medium, 500))',
  titleLargeFont:
    "var(--kui-typography-title-large-font, var(--kui-typography-font-family-brand, 'Roboto Serif', 'Iowan Old Style', Georgia, serif))",
  titleLargeLineHeight: 'var(--kui-typography-title-large-line-height, 28px)',
  titleLargeSize: 'var(--kui-typography-title-large-size, 22px)',
  titleLargeTracking: 'var(--kui-typography-title-large-tracking, 0px)',
  titleLargeWeight:
    'var(--kui-typography-title-large-weight, var(--kui-typography-weight-regular, 400))',
  titleMediumFont:
    "var(--kui-typography-title-medium-font, var(--kui-typography-font-family-plain, 'Roboto Flex', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif))",
  titleMediumLineHeight: 'var(--kui-typography-title-medium-line-height, 24px)',
  titleMediumSize: 'var(--kui-typography-title-medium-size, 16px)',
  titleMediumTracking: 'var(--kui-typography-title-medium-tracking, 0.15px)',
  titleMediumWeight:
    'var(--kui-typography-title-medium-weight, var(--kui-typography-weight-medium, 500))',
  titleSmallFont:
    "var(--kui-typography-title-small-font, var(--kui-typography-font-family-plain, 'Roboto Flex', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif))",
  titleSmallLineHeight: 'var(--kui-typography-title-small-line-height, 20px)',
  titleSmallSize: 'var(--kui-typography-title-small-size, 14px)',
  titleSmallTracking: 'var(--kui-typography-title-small-tracking, 0.1px)',
  titleSmallWeight:
    'var(--kui-typography-title-small-weight, var(--kui-typography-weight-medium, 500))',
  weightBold: 'var(--kui-typography-weight-bold, 700)',
  weightMedium: 'var(--kui-typography-weight-medium, 500)',
  weightRegular: 'var(--kui-typography-weight-regular, 400)',
})

export { typography }

const spacing = stylex.defineVars({
  lg: 'var(--kui-spacing-lg, 16px)',
  md: 'var(--kui-spacing-md, 12px)',
  sm: 'var(--kui-spacing-sm, 8px)',
  xl: 'var(--kui-spacing-xl, 24px)',
  xs: 'var(--kui-spacing-xs, 4px)',
  xxl: 'var(--kui-spacing-xxl, 32px)',
  xxs: 'var(--kui-spacing-xxs, 2px)',
  xxxl: 'var(--kui-spacing-xxxl, 40px)',
})

export { spacing }

const radii = stylex.defineVars({
  circle: 'var(--kui-radius-circle, 9999px)',
  lg: 'var(--kui-radius-lg, 16px)',
  md: 'var(--kui-radius-md, 12px)',
  none: 'var(--kui-radius-none, 0px)',
  pill: 'var(--kui-radius-pill, 9999px)',
  sm: 'var(--kui-radius-sm, 8px)',
  xl: 'var(--kui-radius-xl, 28px)',
  xs: 'var(--kui-radius-xs, 4px)',
})

export { radii }

const sizing = stylex.defineVars({
  controlLg: 'var(--kui-sizing-control-lg, 56px)',
  controlMd: 'var(--kui-sizing-control-md, 48px)',
  controlSm: 'var(--kui-sizing-control-sm, 40px)',
  controlXl: 'var(--kui-sizing-control-xl, 96px)',
  controlXs: 'var(--kui-sizing-control-xs, 32px)',
  controlXxl: 'var(--kui-sizing-control-xxl, 136px)',
  rowLg: 'var(--kui-sizing-row-lg, 88px)',
  rowMd: 'var(--kui-sizing-row-md, 72px)',
  rowSm: 'var(--kui-sizing-row-sm, 56px)',
  rowXs: 'var(--kui-sizing-row-xs, 48px)',
})

export { sizing }

const shadows = stylex.defineVars({
  elevation1:
    'var(--kui-shadow-elevation1, 0px 1px 2px 0px rgba(0, 0, 0, 0.3), 0px 1px 3px 1px rgba(0, 0, 0, 0.15))',
  elevation2:
    'var(--kui-shadow-elevation2, 0px 1px 2px 0px rgba(0, 0, 0, 0.3), 0px 2px 6px 2px rgba(0, 0, 0, 0.15))',
  elevation3:
    'var(--kui-shadow-elevation3, 0px 1px 3px 0px rgba(0, 0, 0, 0.3), 0px 4px 8px 3px rgba(0, 0, 0, 0.15))',
  elevation4:
    'var(--kui-shadow-elevation4, 0px 2px 3px 0px rgba(0, 0, 0, 0.3), 0px 6px 10px 4px rgba(0, 0, 0, 0.15))',
  elevation5:
    'var(--kui-shadow-elevation5, 0px 4px 4px 0px rgba(0, 0, 0, 0.3), 0px 8px 12px 6px rgba(0, 0, 0, 0.15))',
})

export { shadows }

const stateLayerOpacity = stylex.defineVars({
  disabledContainer: 'var(--kui-state-layer-opacity-disabled-container, 0.12)',
  disabledContent: 'var(--kui-state-layer-opacity-disabled-content, 0.38)',
  dragged: 'var(--kui-state-layer-opacity-dragged, 0.16)',
  focus: 'var(--kui-state-layer-opacity-focus, 0.1)',
  hover: 'var(--kui-state-layer-opacity-hover, 0.08)',
  pressed: 'var(--kui-state-layer-opacity-pressed, 0.1)',
})

export { stateLayerOpacity }

const motion = stylex.defineVars({
  durationLong1: 'var(--kui-motion-duration-long1, 450ms)',
  durationLong2: 'var(--kui-motion-duration-long2, 500ms)',
  durationLong3: 'var(--kui-motion-duration-long3, 600ms)',
  durationMedium1: 'var(--kui-motion-duration-medium1, 250ms)',
  durationMedium2: 'var(--kui-motion-duration-medium2, 300ms)',
  durationMedium3: 'var(--kui-motion-duration-medium3, 350ms)',
  durationShort1: 'var(--kui-motion-duration-short1, 100ms)',
  durationShort2: 'var(--kui-motion-duration-short2, 150ms)',
  durationShort3: 'var(--kui-motion-duration-short3, 200ms)',
  easingEmphasized:
    'var(--kui-motion-easing-emphasized, cubic-bezier(0.2, 0, 0, 1))',
  easingEmphasizedAccelerate:
    'var(--kui-motion-easing-emphasized-accelerate, cubic-bezier(0.3, 0, 0.8, 0.15))',
  easingEmphasizedDecelerate:
    'var(--kui-motion-easing-emphasized-decelerate, cubic-bezier(0.05, 0.7, 0.1, 1))',
  easingSpringFast:
    'var(--kui-motion-easing-spring-fast, cubic-bezier(0.34, 1.56, 0.64, 1))',
  easingSpringSlow:
    'var(--kui-motion-easing-spring-slow, cubic-bezier(0.16, 1, 0.3, 1))',
  easingStandard:
    'var(--kui-motion-easing-standard, cubic-bezier(0.2, 0, 0, 1))',
})

export { motion }

const colorsScope = stylex.createTheme(colors, {})
const motionScope = stylex.createTheme(motion, {})
const radiiScope = stylex.createTheme(radii, {})
const shadowsScope = stylex.createTheme(shadows, {})
const sizingScope = stylex.createTheme(sizing, {})
const spacingScope = stylex.createTheme(spacing, {})
const stateLayerOpacityScope = stylex.createTheme(stateLayerOpacity, {})
const typographyScope = stylex.createTheme(typography, {})

const tokenScope = [
  colorsScope,
  motionScope,
  radiiScope,
  shadowsScope,
  sizingScope,
  spacingScope,
  stateLayerOpacityScope,
  typographyScope,
]

export { tokenScope }

const breakpoints = stylex.defineConsts({
  compact: '0px',
  expanded: '840px',
  extraLarge: '1600px',
  large: '1200px',
  medium: '600px',
})

export { breakpoints }

const media = stylex.defineConsts({
  belowExpanded: '@media (width < 840px)',
  belowExtraLarge: '@media (width < 1600px)',
  belowLarge: '@media (width < 1200px)',
  belowMedium: '@media (width < 600px)',
  expanded: '@media (width >= 840px)',
  extraLarge: '@media (width >= 1600px)',
  large: '@media (width >= 1200px)',
  medium: '@media (width >= 600px)',
})

export { media }
