// AUTO-GENERATED by scripts/build-tokens.mjs from the sibling design.tokens.json.
// Do not hand-edit — change design.tokens.json and run `npm run tokens:build`.
//
// Tokens as plain JS values, for the code that cannot take a CSS one. Reach for
// the StyleX theme in design.tokens.stylex.ts anywhere a CSS property value
// will do: those are var(--kui-*, literal) references, so a consumer who
// redeclares the custom property moves them. The literals below are frozen at
// build time and cannot honour such an override, which is the whole cost of
// using them.
//
// So a group appears here only once something has to compute with it rather
// than declare it, which today means two:
//
//   motion  — element.animate() throws a TypeError on a var() duration or
//             easing, and its duration wants a number of milliseconds, so even
//             '450ms' throws. setTimeout coerces a string to NaN and fires
//             immediately, silently.
//   spacing — useRipple does arithmetic with it, growing the ripple past the
//             host's corners by a fixed inset. A var() would concatenate into
//             nonsense rather than add.
//
// Colours, radii, shadows, typography and the state-layer opacities are all
// declared rather than computed, so none of them is generated here.

const motionDurationMs = {
  long1: 450,
  long2: 500,
  long3: 600,
  medium1: 250,
  medium2: 300,
  medium3: 350,
  short1: 100,
  short2: 150,
  short3: 200,
} as const

const motionEasing = {
  emphasized: 'cubic-bezier(0.2, 0, 0, 1)',
  emphasizedAccelerate: 'cubic-bezier(0.3, 0, 0.8, 0.15)',
  emphasizedDecelerate: 'cubic-bezier(0.05, 0.7, 0.1, 1)',
  springFast: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
  springSlow: 'cubic-bezier(0.16, 1, 0.3, 1)',
  standard: 'cubic-bezier(0.2, 0, 0, 1)',
} as const

const spacingPx = {
  lg: 16,
  md: 12,
  sm: 8,
  xl: 24,
  xs: 4,
  xxl: 32,
  xxs: 2,
  xxxl: 40,
} as const

export { motionDurationMs, motionEasing, spacingPx }
