import * as stylex from '@stylexjs/stylex'

import {
  colors,
  radii,
  shadows,
  spacing,
  typography,
} from '../tokens/design.tokens.stylex'

// Four schemes that exist to be looked at. They are Storybook material rather
// than library API — nothing under src/index.ts reaches them — and what they
// document is the shape of a theme rather than a palette anyone should ship.
//
// Each one is a set of `stylex.createTheme` calls over the token groups in
// design.tokens.stylex.ts, which is the same mechanism .storybook/components/
// ThemeWrapper.tsx already applies for light and dark. A consumer outside the
// StyleX toolchain expresses the same thing by redeclaring the matching
// `--kui-*` custom properties on `:root` — see src/tokens/design.tokens.css,
// and the Theming page for the two side by side.
//
// **Only `colors` is stated in full, and it has to be.** Every colour token's
// default is a `prefers-color-scheme` pair, so a key left out of a
// `createTheme` over `colors` falls through to whichever half the reader's OS
// asks for — a dark scheme missing one key renders that role in its light
// value on a light machine. No other group carries a media query, so the
// partial overrides below are read the same way everywhere.
//
// Every foreground/background pair a component actually renders clears WCAG AA
// — 4.5:1 for text, 3:1 for the outline rule — which is the bar the library's
// own light and dark tokens hold to. The a11y addon fails the build otherwise,
// and a scheme is not worth demonstrating if it cannot be read.

const GROTESQUE =
  "'Helvetica Neue', Helvetica, Arial, 'Roboto Flex', sans-serif"

const MONO =
  "ui-monospace, 'SF Mono', 'Roboto Mono', Menlo, Consolas, monospace"

const SANS =
  "'Roboto Flex', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif"

const SERIF = "'Iowan Old Style', 'Palatino Linotype', Palatino, Georgia, serif"

const editorialColors = stylex.createTheme(colors, {
  background: '#fef9f3',
  error: '#b7191c',
  errorContainer: '#ffd2cc',
  inverseOnSurface: '#f7f1e8',
  inversePrimary: '#fea387',
  inverseSurface: '#37322b',
  negative: '#a24102',
  negativeContainer: '#fed4c1',
  onBackground: '#231e18',
  onError: '#fefbfa',
  onErrorContainer: '#4e0405',
  onNegative: '#fefbfa',
  onNegativeContainer: '#431701',
  onPositive: '#f9fdf9',
  onPositiveContainer: '#072f14',
  onPrimary: '#fefbfa',
  onPrimaryContainer: '#421709',
  onPrimaryFixed: '#2d0700',
  onPrimaryFixedVariant: '#79331c',
  onSecondary: '#fdfcf9',
  onSecondaryContainer: '#2c260f',
  onSecondaryFixed: '#1c1601',
  onSecondaryFixedVariant: '#544b25',
  onSurface: '#231e18',
  onSurfaceVariant: '#5b5143',
  onTertiary: '#f9fcff',
  onTertiaryContainer: '#15283b',
  onTertiaryFixed: '#051729',
  onTertiaryFixedVariant: '#2f4d6c',
  outline: '#7e7364',
  outlineVariant: '#cec2b2',
  positive: '#176e35',
  positiveContainer: '#a3f5b4',
  primary: '#9f4325',
  primaryContainer: '#fed3c6',
  primaryFixed: '#fed3c6',
  primaryFixedDim: '#fea387',
  scrim: '#000000',
  secondary: '#6c5f2e',
  secondaryContainer: '#ecdeaa',
  secondaryFixed: '#ecdeaa',
  secondaryFixedDim: '#ccbe8a',
  shadow: '#000000',
  surface: '#fef9f3',
  surfaceBright: '#fefbf7',
  surfaceContainer: '#f7f0e7',
  surfaceContainerHigh: '#f1eae1',
  surfaceContainerHighest: '#ebe4db',
  surfaceContainerLow: '#fcf5ec',
  surfaceContainerLowest: '#ffffff',
  surfaceDim: '#e4ddd4',
  surfaceTint: '#9f4325',
  surfaceVariant: '#efe3d2',
  tertiary: '#3b638c',
  tertiaryContainer: '#c6e1ff',
  tertiaryFixed: '#c6e1ff',
  tertiaryFixedDim: '#97c2f0',
})

const editorialTypography = stylex.createTheme(typography, {
  bodyLargeFont: SERIF,
  bodyLargeLineHeight: '28px',
  bodyLargeSize: '17px',
  bodyLargeTracking: '0px',
  bodyMediumFont: SERIF,
  bodyMediumLineHeight: '24px',
  bodyMediumSize: '15px',
  bodyMediumTracking: '0px',
  bodySmallFont: SERIF,
  bodySmallLineHeight: '20px',
  bodySmallSize: '13px',
  bodySmallTracking: '0px',
  displayLargeFont: SERIF,
  displayLargeTracking: '-1px',
  displayMediumFont: SERIF,
  displayMediumTracking: '-0.5px',
  displaySmallFont: SERIF,
  displaySmallTracking: '-0.5px',
  fontFamilyBrand: SERIF,
  fontFamilyPlain: SERIF,
  headlineLargeFont: SERIF,
  headlineLargeTracking: '-0.5px',
  headlineMediumFont: SERIF,
  headlineMediumTracking: '-0.25px',
  headlineSmallFont: SERIF,
  labelLargeFont: SERIF,
  labelLargeTracking: '0px',
  labelLargeWeight: '600',
  labelMediumFont: SERIF,
  labelMediumTracking: '0px',
  labelSmallFont: SERIF,
  labelSmallTracking: '0px',
  titleLargeFont: SERIF,
  titleLargeLineHeight: '32px',
  titleLargeSize: '24px',
  titleMediumFont: SERIF,
  titleSmallFont: SERIF,
})

const editorialRadii = stylex.createTheme(radii, {
  full: '9999px',
  lg: '6px',
  md: '4px',
  none: '0px',
  sm: '3px',
  xl: '10px',
  xs: '2px',
})

const editorialShadows = stylex.createTheme(shadows, {
  elevation1: '0px 1px 2px 0px rgba(67, 41, 20, 0.12)',
  elevation2: '0px 2px 6px 0px rgba(67, 41, 20, 0.14)',
  elevation3: '0px 4px 12px 0px rgba(67, 41, 20, 0.16)',
  elevation4: '0px 8px 20px 0px rgba(67, 41, 20, 0.18)',
  elevation5: '0px 14px 32px 0px rgba(67, 41, 20, 0.2)',
})

const editorialSpacing = stylex.createTheme(spacing, {
  lg: '20px',
  md: '14px',
  sm: '10px',
  xl: '32px',
  xs: '6px',
  xxl: '44px',
  xxs: '3px',
  xxxl: '56px',
})

const neonColors = stylex.createTheme(colors, {
  background: '#130f1a',
  error: '#ffa098',
  errorContainer: '#940015',
  inverseOnSurface: '#2a2732',
  inversePrimary: '#aa0389',
  inverseSurface: '#e0dbeb',
  negative: '#ffa383',
  negativeContainer: '#852b00',
  onBackground: '#e6e2f1',
  onError: '#2f2726',
  onErrorContainer: '#fed2cd',
  onNegative: '#2e2725',
  onNegativeContainer: '#fed3c4',
  onPositive: '#252a27',
  onPositiveContainer: '#a7f2c9',
  onPrimary: '#2e262b',
  onPrimaryContainer: '#fecded',
  onPrimaryFixed: '#2d0022',
  onPrimaryFixedVariant: '#85096a',
  onSecondary: '#29282d',
  onSecondaryContainer: '#e0d8ff',
  onSecondaryFixed: '#1b063b',
  onSecondaryFixedVariant: '#54388e',
  onSurface: '#e6e2f1',
  onSurfaceVariant: '#c1b8d4',
  onTertiary: '#242a2b',
  onTertiaryContainer: '#9aeff4',
  onTertiaryFixed: '#011a1c',
  onTertiaryFixedVariant: '#02575b',
  outline: '#9087a1',
  outlineVariant: '#504860',
  positive: '#30de97',
  positiveContainer: '#025c3b',
  primary: '#fe94dd',
  primaryContainer: '#86016b',
  primaryFixed: '#ffcded',
  primaryFixedDim: '#fe94dd',
  scrim: '#000000',
  secondary: '#c3affe',
  secondaryContainer: '#572e9d',
  secondaryFixed: '#e0d8ff',
  secondaryFixedDim: '#c3affe',
  shadow: '#000000',
  surface: '#130f1a',
  surfaceBright: '#3f3b47',
  surfaceContainer: '#201c27',
  surfaceContainerHigh: '#2a2732',
  surfaceContainerHighest: '#34303d',
  surfaceContainerLow: '#1a1621',
  surfaceContainerLowest: '#08060f',
  surfaceDim: '#130f1a',
  surfaceTint: '#fe94dd',
  surfaceVariant: '#3b334a',
  tertiary: '#00d7e0',
  tertiaryContainer: '#04585c',
  tertiaryFixed: '#62f7ff',
  tertiaryFixedDim: '#00d7e0',
})

const neonTypography = stylex.createTheme(typography, {
  bodyLargeFont: SANS,
  bodyMediumFont: SANS,
  bodySmallFont: SANS,
  displayLargeFont: SANS,
  displayLargeTracking: '-1.5px',
  displayLargeWeight: '700',
  displayMediumFont: SANS,
  displayMediumTracking: '-1px',
  displayMediumWeight: '700',
  displaySmallFont: SANS,
  displaySmallTracking: '-1px',
  displaySmallWeight: '700',
  fontFamilyBrand: SANS,
  fontFamilyPlain: SANS,
  headlineLargeFont: SANS,
  headlineLargeTracking: '-0.5px',
  headlineLargeWeight: '700',
  headlineMediumFont: SANS,
  headlineMediumTracking: '-0.5px',
  headlineMediumWeight: '700',
  headlineSmallFont: SANS,
  headlineSmallTracking: '-0.25px',
  headlineSmallWeight: '700',
  labelLargeFont: SANS,
  labelLargeTracking: '0.8px',
  labelLargeWeight: '700',
  labelMediumFont: SANS,
  labelMediumTracking: '0.8px',
  labelMediumWeight: '700',
  labelSmallFont: SANS,
  labelSmallTracking: '0.8px',
  labelSmallWeight: '700',
  titleLargeFont: SANS,
  titleLargeWeight: '700',
  titleMediumFont: SANS,
  titleMediumWeight: '600',
  titleSmallFont: SANS,
  titleSmallWeight: '600',
})

const neonRadii = stylex.createTheme(radii, {
  full: '9999px',
  lg: '26px',
  md: '20px',
  none: '0px',
  sm: '14px',
  xl: '34px',
  xs: '10px',
})

const neonShadows = stylex.createTheme(shadows, {
  elevation1: '0px 0px 8px 0px rgba(254, 148, 221, 0.22)',
  elevation2: '0px 0px 14px 0px rgba(254, 148, 221, 0.3)',
  elevation3: '0px 0px 22px 0px rgba(254, 148, 221, 0.38)',
  elevation4: '0px 0px 30px 0px rgba(195, 175, 254, 0.44)',
  elevation5: '0px 0px 40px 0px rgba(0, 215, 224, 0.5)',
})

const neonSpacing = stylex.createTheme(spacing, {
  lg: '16px',
  md: '12px',
  sm: '8px',
  xl: '24px',
  xs: '4px',
  xxl: '32px',
  xxs: '2px',
  xxxl: '40px',
})

const nordicColors = stylex.createTheme(colors, {
  background: '#e2eefe',
  error: '#a92e2e',
  errorContainer: '#fed2cd',
  inverseOnSurface: '#eaf3ff',
  inversePrimary: '#9ebdff',
  inverseSurface: '#273445',
  negative: '#9c3f03',
  negativeContainer: '#fed4c1',
  onBackground: '#182535',
  onError: '#fefbfa',
  onErrorContainer: '#480e0e',
  onNegative: '#fefbf9',
  onNegativeContainer: '#431700',
  onPositive: '#f8fdfa',
  onPositiveContainer: '#062f19',
  onPrimary: '#fafcff',
  onPrimaryContainer: '#13244c',
  onPrimaryFixed: '#051238',
  onPrimaryFixedVariant: '#2d4888',
  onSecondary: '#f8fdfd',
  onSecondaryContainer: '#012d2f',
  onSecondaryFixed: '#001a1c',
  onSecondaryFixedVariant: '#00565a',
  onSurface: '#182535',
  onSurfaceVariant: '#3a4e68',
  onTertiary: '#fcfbff',
  onTertiaryContainer: '#2c203a',
  onTertiaryFixed: '#1b0f28',
  onTertiaryFixedVariant: '#54406a',
  outline: '#566b86',
  outlineVariant: '#a2bad8',
  positive: '#0a693c',
  positiveContainer: '#a1f4be',
  primary: '#3557aa',
  primaryContainer: '#cfdeff',
  primaryFixed: '#cfdeff',
  primaryFixedDim: '#9ebdff',
  scrim: '#000000',
  secondary: '#03666a',
  secondaryContainer: '#92f1f6',
  secondaryFixed: '#92f1f6',
  secondaryFixedDim: '#71d0d5',
  shadow: '#000000',
  surface: '#e2eefe',
  surfaceBright: '#edf4fe',
  surfaceContainer: '#d3e4fa',
  surfaceContainerHigh: '#cddef4',
  surfaceContainerHighest: '#c8d9ee',
  surfaceContainerLow: '#d8e9ff',
  surfaceContainerLowest: '#f7faff',
  surfaceDim: '#cadbf1',
  surfaceTint: '#3557aa',
  surfaceVariant: '#c7dffe',
  tertiary: '#695086',
  tertiaryContainer: '#e7d5ff',
  tertiaryFixed: '#e7d5ff',
  tertiaryFixedDim: '#cbafed',
})

const nordicTypography = stylex.createTheme(typography, {
  bodyLargeFont: SANS,
  bodyLargeLineHeight: '28px',
  bodyMediumFont: SANS,
  bodyMediumLineHeight: '24px',
  bodySmallFont: SANS,
  bodySmallLineHeight: '18px',
  displayLargeFont: SANS,
  displayLargeTracking: '-0.5px',
  displayLargeWeight: '300',
  displayMediumFont: SANS,
  displayMediumWeight: '300',
  displaySmallFont: SANS,
  displaySmallWeight: '300',
  fontFamilyBrand: SANS,
  fontFamilyPlain: SANS,
  headlineLargeFont: SANS,
  headlineLargeWeight: '300',
  headlineMediumFont: SANS,
  headlineMediumWeight: '300',
  headlineSmallFont: SANS,
  headlineSmallWeight: '400',
  labelLargeFont: SANS,
  labelLargeTracking: '0.4px',
  labelMediumFont: SANS,
  labelMediumTracking: '0.4px',
  labelSmallFont: SANS,
  labelSmallTracking: '0.4px',
  titleLargeFont: SANS,
  titleLargeWeight: '400',
  titleMediumFont: SANS,
  titleMediumWeight: '500',
  titleSmallFont: SANS,
})

const nordicRadii = stylex.createTheme(radii, {
  full: '9999px',
  lg: '32px',
  md: '24px',
  none: '0px',
  sm: '16px',
  xl: '44px',
  xs: '10px',
})

const nordicShadows = stylex.createTheme(shadows, {
  elevation1: '0px 2px 6px 0px rgba(24, 39, 58, 0.07)',
  elevation2: '0px 4px 14px 0px rgba(24, 39, 58, 0.09)',
  elevation3: '0px 8px 24px 0px rgba(24, 39, 58, 0.11)',
  elevation4: '0px 14px 36px 0px rgba(24, 39, 58, 0.13)',
  elevation5: '0px 22px 52px 0px rgba(24, 39, 58, 0.15)',
})

const nordicSpacing = stylex.createTheme(spacing, {
  lg: '20px',
  md: '14px',
  sm: '10px',
  xl: '30px',
  xs: '6px',
  xxl: '42px',
  xxs: '3px',
  xxxl: '52px',
})

const posterColors = stylex.createTheme(colors, {
  background: '#ffedab',
  error: '#ab0b71',
  errorContainer: '#ffa3cf',
  inverseOnSurface: '#fff2c3',
  inversePrimary: '#ff9f9f',
  inverseSurface: '#3d3202',
  negative: '#a92900',
  negativeContainer: '#ffac97',
  onBackground: '#211a01',
  onError: '#fefbfc',
  onErrorContainer: '#2f001b',
  onNegative: '#fefbfa',
  onNegativeContainer: '#2f0500',
  onPositive: '#f8fef8',
  onPositiveContainer: '#001d03',
  onPrimary: '#fffbfa',
  onPrimaryContainer: '#320006',
  onPrimaryFixed: '#320006',
  onPrimaryFixedVariant: '#930123',
  onSecondary: '#fbfcfe',
  onSecondaryContainer: '#020e42',
  onSecondaryFixed: '#020e42',
  onSecondaryFixedVariant: '#25459a',
  onSurface: '#211a01',
  onSurfaceVariant: '#564700',
  onTertiary: '#f8fef8',
  onTertiaryContainer: '#001d03',
  onTertiaryFixed: '#001d03',
  onTertiaryFixedVariant: '#035c15',
  outline: '#766202',
  outlineVariant: '#c7b05a',
  positive: '#026719',
  positiveContainer: '#75e07c',
  primary: '#b4002d',
  primaryContainer: '#feaaa9',
  primaryFixed: '#fed2d0',
  primaryFixedDim: '#ff9f9f',
  scrim: '#000000',
  secondary: '#2850be',
  secondaryContainer: '#a8c4fe',
  secondaryFixed: '#cfdeff',
  secondaryFixedDim: '#9ebdff',
  shadow: '#000000',
  surface: '#ffedab',
  surfaceBright: '#fff7d9',
  surfaceContainer: '#ffde5d',
  surfaceContainerHigh: '#fad746',
  surfaceContainerHighest: '#f4d13d',
  surfaceContainerLow: '#ffe687',
  surfaceContainerLowest: '#fffae8',
  surfaceDim: '#f5d240',
  surfaceTint: '#b4002d',
  surfaceVariant: '#f0d982',
  tertiary: '#026719',
  tertiaryContainer: '#75e07c',
  tertiaryFixed: '#90fb95',
  tertiaryFixedDim: '#6fda75',
})

const posterTypography = stylex.createTheme(typography, {
  bodyLargeFont: GROTESQUE,
  bodyLargeLineHeight: '26px',
  bodyLargeSize: '17px',
  bodyLargeWeight: '500',
  bodyMediumFont: GROTESQUE,
  bodyMediumWeight: '500',
  bodySmallFont: GROTESQUE,
  bodySmallWeight: '500',
  displayLargeFont: GROTESQUE,
  displayLargeLineHeight: '72px',
  displayLargeSize: '72px',
  displayLargeTracking: '-3px',
  displayLargeWeight: '900',
  displayMediumFont: GROTESQUE,
  displayMediumLineHeight: '56px',
  displayMediumSize: '56px',
  displayMediumTracking: '-2px',
  displayMediumWeight: '900',
  displaySmallFont: GROTESQUE,
  displaySmallLineHeight: '46px',
  displaySmallSize: '44px',
  displaySmallTracking: '-1.5px',
  displaySmallWeight: '900',
  fontFamilyBrand: GROTESQUE,
  fontFamilyPlain: GROTESQUE,
  headlineLargeFont: GROTESQUE,
  headlineLargeLineHeight: '38px',
  headlineLargeSize: '36px',
  headlineLargeTracking: '-1px',
  headlineLargeWeight: '800',
  headlineMediumFont: GROTESQUE,
  headlineMediumLineHeight: '32px',
  headlineMediumSize: '30px',
  headlineMediumTracking: '-0.75px',
  headlineMediumWeight: '800',
  headlineSmallFont: GROTESQUE,
  headlineSmallLineHeight: '26px',
  headlineSmallSize: '24px',
  headlineSmallTracking: '-0.5px',
  headlineSmallWeight: '800',
  labelLargeFont: GROTESQUE,
  labelLargeTracking: '0.6px',
  labelLargeWeight: '800',
  labelMediumFont: GROTESQUE,
  labelMediumTracking: '0.6px',
  labelMediumWeight: '800',
  labelSmallFont: GROTESQUE,
  labelSmallTracking: '0.6px',
  labelSmallWeight: '800',
  titleLargeFont: GROTESQUE,
  titleLargeLineHeight: '26px',
  titleLargeSize: '22px',
  titleLargeTracking: '-0.25px',
  titleLargeWeight: '800',
  titleMediumFont: GROTESQUE,
  titleMediumWeight: '700',
  titleSmallFont: GROTESQUE,
  titleSmallWeight: '700',
  weightBold: '900',
  weightMedium: '700',
  weightRegular: '500',
})

const posterRadii = stylex.createTheme(radii, {
  full: '9999px',
  lg: '0px',
  md: '0px',
  none: '0px',
  sm: '0px',
  xl: '0px',
  xs: '0px',
})

const posterShadows = stylex.createTheme(shadows, {
  elevation1: '2px 2px 0px 0px #2a2000',
  elevation2: '4px 4px 0px 0px #2a2000',
  elevation3: '6px 6px 0px 0px #2a2000',
  elevation4: '9px 9px 0px 0px #2a2000',
  elevation5: '13px 13px 0px 0px #2a2000',
})

const posterSpacing = stylex.createTheme(spacing, {
  lg: '22px',
  md: '16px',
  sm: '10px',
  xl: '34px',
  xs: '6px',
  xxl: '48px',
  xxs: '3px',
  xxxl: '64px',
})

const terminalColors = stylex.createTheme(colors, {
  background: '#0e130f',
  error: '#ffa098',
  errorContainer: '#940015',
  inverseOnSurface: '#252b26',
  inversePrimary: '#04702b',
  inverseSurface: '#d9e0da',
  negative: '#ffa666',
  negativeContainer: '#773a00',
  onBackground: '#dfe7e0',
  onError: '#2e2726',
  onErrorContainer: '#fed2cd',
  onNegative: '#2d2824',
  onNegativeContainer: '#fed4b9',
  onPositive: '#262a26',
  onPositiveContainer: '#b5efbf',
  onPrimary: '#262a26',
  onPrimaryContainer: '#b4f0bb',
  onPrimaryFixed: '#001d06',
  onPrimaryFixedVariant: '#025b21',
  onSecondary: '#252a2a',
  onSecondaryContainer: '#afebea',
  onSecondaryFixed: '#001b1b',
  onSecondaryFixedVariant: '#015657',
  onSurface: '#dfe7e0',
  onSurfaceVariant: '#b3c2b6',
  onTertiary: '#2a2924',
  onTertiaryContainer: '#eedea4',
  onTertiaryFixed: '#1c1600',
  onTertiaryFixedVariant: '#594a01',
  outline: '#818f83',
  outlineVariant: '#445146',
  positive: '#66da85',
  positiveContainer: '#035d28',
  primary: '#65db7c',
  primaryContainer: '#035e23',
  primaryFixed: '#87fc9c',
  primaryFixedDim: '#65db7c',
  scrim: '#000000',
  secondary: '#57d4d4',
  secondaryContainer: '#055959',
  secondaryFixed: '#7bf5f5',
  secondaryFixedDim: '#57d4d4',
  shadow: '#000000',
  surface: '#0e130f',
  surfaceBright: '#393f3a',
  surfaceContainer: '#1a201b',
  surfaceContainerHigh: '#252b26',
  surfaceContainerHighest: '#2f3530',
  surfaceContainerLow: '#141a15',
  surfaceContainerLowest: '#050905',
  surfaceDim: '#0e130f',
  surfaceTint: '#65db7c',
  surfaceVariant: '#2f3c31',
  tertiary: '#dabc43',
  tertiaryContainer: '#5c4c00',
  tertiaryFixed: '#fbdd67',
  tertiaryFixedDim: '#dabc43',
})

const terminalTypography = stylex.createTheme(typography, {
  bodyLargeFont: MONO,
  bodyLargeTracking: '0px',
  bodyMediumFont: MONO,
  bodyMediumTracking: '0px',
  bodySmallFont: MONO,
  bodySmallTracking: '0px',
  displayLargeFont: MONO,
  displayLargeLineHeight: '48px',
  displayLargeSize: '40px',
  displayLargeTracking: '-1px',
  displayMediumFont: MONO,
  displayMediumLineHeight: '40px',
  displayMediumSize: '32px',
  displaySmallFont: MONO,
  displaySmallLineHeight: '34px',
  displaySmallSize: '26px',
  fontFamilyBrand: MONO,
  fontFamilyMono: MONO,
  fontFamilyPlain: MONO,
  headlineLargeFont: MONO,
  headlineLargeLineHeight: '32px',
  headlineLargeSize: '24px',
  headlineMediumFont: MONO,
  headlineMediumLineHeight: '28px',
  headlineMediumSize: '21px',
  headlineSmallFont: MONO,
  headlineSmallLineHeight: '26px',
  headlineSmallSize: '18px',
  labelLargeFont: MONO,
  labelLargeTracking: '0.5px',
  labelMediumFont: MONO,
  labelMediumTracking: '0.5px',
  labelSmallFont: MONO,
  labelSmallTracking: '0.5px',
  titleLargeFont: MONO,
  titleLargeLineHeight: '24px',
  titleLargeSize: '17px',
  titleMediumFont: MONO,
  titleSmallFont: MONO,
})

const terminalRadii = stylex.createTheme(radii, {
  full: '2px',
  lg: '0px',
  md: '0px',
  none: '0px',
  sm: '0px',
  xl: '0px',
  xs: '0px',
})

const terminalShadows = stylex.createTheme(shadows, {
  elevation1: '0px 0px 0px 1px rgba(101, 219, 124, 0.24)',
  elevation2: '0px 0px 0px 1px rgba(101, 219, 124, 0.36)',
  elevation3: '0px 0px 0px 1px rgba(101, 219, 124, 0.48)',
  elevation4: '0px 0px 0px 1px rgba(101, 219, 124, 0.62)',
  elevation5: '0px 0px 0px 1px rgba(101, 219, 124, 0.78)',
})

const terminalSpacing = stylex.createTheme(spacing, {
  lg: '14px',
  md: '10px',
  sm: '6px',
  xl: '20px',
  xs: '4px',
  xxl: '28px',
  xxs: '2px',
  xxxl: '36px',
})

type DemoTheme = {
  /** What the scheme is going for, in a sentence. */
  description: string
  /** What the toolbar and the sidebar call it. */
  label: string
  /** The scheme itself, ready to hand to `stylex.props`. */
  theme: stylex.CompiledStyles[]
}

// The toolbar's Theme control and the Theming page are both built from this,
// so a scheme added here needs nothing else to appear in either.
const demoThemes = {
  editorial: {
    description:
      'Ink on warm paper, set in a serif at a reading size, with tight radii and shadows that barely lift.',
    label: 'Editorial',
    theme: [
      editorialColors,
      editorialTypography,
      editorialRadii,
      editorialShadows,
      editorialSpacing,
    ],
  },
  neon: {
    description:
      'Magenta and cyan on violet-black, heavy sans, fully rounded, lit by coloured glows rather than drop shadows.',
    label: 'Neon',
    theme: [neonColors, neonTypography, neonRadii, neonShadows, neonSpacing],
  },
  nordic: {
    description:
      'Indigo and teal over a pale blue ground rather than a white one, set in light weights at open line heights, and rounded far enough that nothing on the page keeps a square corner.',
    label: 'Nordic',
    theme: [
      nordicColors,
      nordicTypography,
      nordicRadii,
      nordicShadows,
      nordicSpacing,
    ],
  },
  poster: {
    description:
      'Vermilion and ultramarine on a saturated yellow ground, set in a heavy grotesque at poster sizes, with square panels, pill controls, and shadows that are hard offsets rather than blur.',
    label: 'Poster',
    theme: [
      posterColors,
      posterTypography,
      posterRadii,
      posterShadows,
      posterSpacing,
    ],
  },
  terminal: {
    description:
      'Phosphor green on near-black, monospaced throughout, square-cornered, with a ring in place of every shadow.',
    label: 'Terminal',
    theme: [
      terminalColors,
      terminalTypography,
      terminalRadii,
      terminalShadows,
      terminalSpacing,
    ],
  },
} satisfies Record<string, DemoTheme>

type DemoThemeName = keyof typeof demoThemes

export type { DemoTheme, DemoThemeName }
export { demoThemes }
